# http://eslint.org/docs/rules/
extends:
  - eslint:recommended
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  node: true
  mocha: true
  es6: true
rules:
  complexity: [ warn, 10 ]
  semi: [ error, never ]
  no-case-declarations: warn
  no-console: off
  new-cap: off
  strict: off
  no-use-before-define: off
  eol-last: off
  quotes: [ warn, single, avoidEscape: true ]
  prettier/prettier: warn
